### ISSUE TITLE
Update EGO-UI to Latest Dependencies as of Jan 7, 2020

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/ego-ui#106]
Update EGO-UI to latest dependencies as of Jan 7, 2020, prior to making changes to remove User Creation and Name field references

**Comment by anncatton** [comment]
Some of the issues dependabot is calling out are from `react-scripts-ts`, which has not had a new release since `3.1.0`. Fixing these dependencies will mean upgrading to a new version of CRA, which I expect will be more involved so will move that part to a separate ticket. This ticket will address the axios and lodash updates only.

**Comment by anncatton** [comment]
Ticket for addressing `react-scripts-ts` dependency issues: https://github.com/overture-stack/ego-ui/issues/108

**Comment by b-f-chan** [comment]
Smoke test on Staging successful, no untowards behaviour observed in basic functions
